// examples/react/App.js
import React from 'react'
import { Query } from 'react-apollo'
import gql from '../../'
import RateCard from './RateCard'

const App = () => (
  <Query
    query={gql`
      {
        rates(currency: "USD") {
          ${RateCard.fragments.rate}
        }
      }
    `}
  >
    {({ loading, error, data }) => {
      if (loading) return <p>Loading...</p>
      if (error) return <p>Error :(</p>

      return data.rates.map(rate => (
        <RateCard key={rate.currency} rate={rate} />
      ))
    }}
  </Query>
)

export default App

// examples/vue/App.vue
<template lang="html">
  <div class="apollo">
    <div v-if="$apollo.loading">Loading...</div>
    <div v-else-if="$apollo.error">Error :(</div>
    <RateCard v-else v-for="rate in rates" :key="rate.currency" :rate="rate" />
  </div>
</template>

<script>
import RateCard from './RateCard';
import gql from 'graphql-tag';

export default {
  components: {
    RateCard
  },

  apollo: {
    rates: gql`{
      rates(currency: "USD") {
        ${RateCard.fragments.rate}
      }
    }`,
  },

  data () {
    return {
      rates: '',
    }
  }
}
</script>
